apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor-api
  template:
    metadata:
      labels:
        app: iot-sensor-api
    spec:
      containers:
        - name: iot-sensor-api
          image: your-dockerhub-username/iot-sensor-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
